apiVersion: apps/v1
kind: Deployment
metadata:
  name: porodnica-webapi
spec:
  template:
    spec:
      containers:
        - name: openapi-ui
          env:
            - name: URL
              value: /porodnica-openapi
            - name: BASE_URL
              value: /porodnica-openapi-ui