apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: porodnica-ambulance-ufe-content
spec:
  microFrontend: porodnica-ambulance-ufe
  element: porodnica-ambulance-home
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?porodnica-ambulance(/.*)?$"