apiVersion: polyfea.github.io/v1alpha1
kind: WebComponent
metadata:
  name: porodnica-ambulance-ufe-content
spec:
  microFrontend: porodnica-ambulance-ufe
  element: porodnica-ambulance-home-app
  attributes:
    - name: base-path
      value: /ambulance-home/
    - name: api-base
      value: http://localhost:30081/api
    - name: porodnica-id
      value: bobulova
  displayRules:
    - allOf:
      - context-name: main-content
      - path: "^(\\.?/)?porodnica-ambulance(/.*)?$"